{% set name = "llckbdm" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llckbdm-{{ version }}.tar.gz
  sha256: 73d388c3f3fe3cbc5c3eec2fb18039556fb838b1a1c006a31db54987fbcde10e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - attrs
    - hdbscan
    - numpy
    - pandas
    - python >=3.6
    - scipy
    - scikit-learn

test:
  imports:
    - llckbdm
    - llckbdm._tests
    - llckbdm.kbdm
    - llckbdm.llckbdm
    - llckbdm.metrics
    - llckbdm.sampling
    - llckbdm.sig_gen
    - llckbdm.min_rmse_kbdm
about:
  home: https://github.com/danilomendesdias/llckbdm
  summary: Line List Clustering Krylov Basis Diagonalization Method implementation in Python
  dev_url: https://github.com/danilomendesdias/llckbdm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danilomendesdias
